### ISSUE TITLE
Investigate Front-end possibilities

### ISSUE THREAD

**Issue by sasharek** [palachi/drawio#11]
Our product should have specialized Front-end (Web).
There are different options:
- Customize DrawIO
- Create a new wrapper around MxGraph

We also can use different technologies:
 - REACT
- Angular

There is also an option to use Eclipse based Web UI
Andrey have some knowledge about it.

**Comment by akaraulov** [comment]
The link to EMF.Cloud: https://www.eclipse.org/emfcloud/
Very briefly: we may utilize well-known Eclipse API (EMF, Ecore and so on) to build web-based modeling tools

**Comment by sasharek** [comment]
Andrey's suggestion to use eclipse-theia/theia was accepted and approved as the main front-end for the product
